### ISSUE TITLE
Looping AssertionError

### ISSUE THREAD

**Issue by datmospro** [freeconga/congatudo-add-on#24]
Hi, just installing the addon i can see the next errors on the registry looping:

```
[2021-12-29T09:23:01.003Z] [ERROR] AssertionError [ERR_ASSERTION]: read(1): empty value from stream
    at read (/snapshot/app/node_modules/@agnoc/core/lib/utils/stream.util.js:21:25)
    at readCleanRoomInfoList (/snapshot/app/node_modules/@agnoc/core/lib/decoders/map.decoder.js:109:36)
    at readCleanPlanList (/snapshot/app/node_modules/@agnoc/core/lib/decoders/map.decoder.js:128:26)
    at decodeArea (/snapshot/app/node_modules/@agnoc/core/lib/decoders/area.decoder.js:42:51)
    at fromBuffer (/snapshot/app/node_modules/@agnoc/core/lib/value-objects/payload.value-object.js:69:12)
    at Function.fromBuffer (/snapshot/app/node_modules/@agnoc/core/lib/value-objects/payload.value-object.js:138:20)
    at unpack (/snapshot/app/node_modules/@agnoc/core/lib/value-objects/packet.value-object.js:48:36)
    at Function.fromBuffer (/snapshot/app/node_modules/@agnoc/core/lib/value-objects/packet.value-object.js:128:23)
    at PacketSocket.onReadable (/snapshot/app/node_modules/@agnoc/core/lib/sockets/packet.socket.js:124:33)
    at processImmediate (node:internal/timers:464:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}
[2021-12-29T09:23:04.991Z] [ERROR] unhandledRejection {
  reason: DomainException: Timeout waiting for response from opcode 'DEVICE_MAPID_GET_GLOBAL_INFO_RSP'
      at Timeout.fail [as _onTimeout] (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:1181:16)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7) {
    metadata: undefined
  },
  stack: "DomainException: Timeout waiting for response from opcode 'DEVICE_MAPID_GET_GLOBAL_INFO_RSP'\n" +
    '    at Timeout.fail [as _onTimeout] (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:1181:16)\n' +
    '    at listOnTimeout (node:internal/timers:557:17)\n' +
    '    at processTimers (node:internal/timers:500:7)',
  promise: Promise {
    <rejected> DomainException: Timeout waiting for response from opcode 'DEVICE_MAPID_GET_GLOBAL_INFO_RSP'
        at Timeout.fail [as _onTimeout] (/snapshot/app/node_modules/@agnoc/core/lib/emitters/robot.emitter.js:1181:16)
        at listOnTimeout (node:internal/timers:557:17)
        at processTimers (node:internal/timers:500:7) {
      metadata: undefined
    }
  }
}
```

But the connection to the robot is correct, i can to some actions and the robot reacts.
But for example if i send de robot to start cleaning, it starts move out from de base, but after 2 seconds it stops (because de addon on Hassio Stops) and turn to the base. And i can see this error on the Web UI:

https://community-assets.home-assistant.io/original/4X/5/5/5/55595d6c12fd465890b9481826725a156e743dd7.png

I reinstalled the addon several times, Don't know what to do.

Thanks.

**Comment by adrigzr** [comment]
Hi @datmospro, what model is your model? Try to clicking on the reset map button `Settings > Persistance Data > Reset map` and run the robot in a full clean.

**Comment by datmospro** [comment]
Omg thats it.... a lot of hours doing sh** and was taht -.- Sorry.

Seems to work perfect now!

Its a 3490.

Many thanks !!!!
